module.exports = Object.freeze({
  SFW_DEV: 'Software Development',
  CUST_SERV: 'Customer Service',
  MKT: 'Marketing',
  FT: 'Full-Time',
  PT: 'Part-Time',
  ATS: 'ATS',
  URL: 'URL',
  ONE_MONTH: '1-month',
  TWO_MONTH: '2-month',
  THREE_MONTH: '3-month',
  SIX_MONTH: '6-month',
  // ONE_YEAR: 'year',
  APPLIED: 'applied',
  REJECTED: 'rejected',
  L1: 'l1',
  L2: 'l2',
  HR: 'hr',
  SELECTED: 'selected',
});
