module.exports = Object.freeze({
  SFW_DEV: 'Software Development',
  CUST_SERV: 'Customer Service',
  MKT: 'Marketing',
  FT: 'Full-Time',
  PT: 'Part-Time',
  INTERN: 'Internship',
  ATS: 'ATS',
  URL: 'URL',
  EMAIL: 'EMAIL',
  ONE_MONTH: '1 Month',
  TWO_MONTH: '2 Month',
  THREE_MONTH: '3 Month',
  SIX_MONTH: '6-month',
  APPLIED: 'Applied',
  REJECTED: 'Rejected',
  TECHNICAL_TEST: 'Technical Test',
  TECHNICAL_INTERVIEW: 'Technical Interview',
  FINAL_INTERVIEW: 'Final Interview',
  SELECTED: 'Selected',
  STATUS_CHANGE: 'statusChange',
  JOB_EXPIRY: 'jobExpiry',
  JOB_EXPIRY_REMINDER: 'jobExpiryReminder',
  JOB_EXPIRY_REMINDER_DAYS: 3,
});
